version: "3.8"
services:
  server:
    image: rancher/rancher:v2.7.10
    privileged: true
    restart: always
    environment:
      CATTLE_SYSTEM_DEFAULT_REGISTRY: "localhost:5000/sviv-docker"
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - type: volume
        source: cni
        target: /var/lib/cni
      - type: volume
        source: data
        target: /var/lib/rancher-data
      - type: volume
        source: kubelet
        target: /var/lib/kubelet
      - type: volume
        source: log
        target: /var/log
      - type: volume
        source: rancher
        target: /var/lib/rancher

volumes:
  cni:
  data:
  kubelet:
  log:
  rancher: