version: '3.8'

services:
  angie:
    image: nginx:latest
    container_name: angie
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin123"
      MINIO_BROWSER_REDIRECT_URL: "http://example/minio/ui"  # Указываем URL для редиректа на консоль
    volumes:
      - data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
volumes:
 data:
