version: '3.8'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - data:/data
    restart: always

  angie:
    image: angie:latest
    container_name: angie
    depends_on:
      - minio
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/angie/default.conf:ro
    restart: always
